# -*- coding: utf-8 -*-
"""session13 pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aGm-vMb-jB04L0eBXDt7ToZPwcwn6RYr
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

ipl = pd.read_csv("data.csv")

print(ipl.head(10))

import pandas as pd

ipl = pd.read_csv("dataset.csv")

runs = ipl["runs"]

print("Mean:", runs.mean())
print("Median:", runs.median())
print("Mode:", runs.mode().tolist())
print("Minimum:", runs.min())
print("Maximum:", runs.max())

import pandas as pd

zomato = pd.DataFrame({
    "name": [
        "Dominos",
        "Burger King",
        "Theobroma",
        "Barbeque Nation",
        "Subway"
    ],
    "rating": [4.2, 4.0, 4.5, 4.3, 3.9],
    "votes": [1200, 950, 1800, 1500, 700],
    "avg_cost": [500, 400, 600, 900, 350]
})

print(zomato)

correlation = zomato["rating"].corr(zomato["votes"])

print("Correlation between rating and votes:", correlation)

import pandas as pd

from google.colab import files
uploaded = files.upload()

ipl = pd.read_csv("data.csv")

summary = ipl.describe()

print(summary)

