# -*- coding: utf-8 -*-
"""Session 1 Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15CRUDXhTi_Z6hla_cTZLiHcjT8V1yQvj
"""

pip install pandas

import pandas as pd

fav_cricket_teams = pd.Series([
    "Mumbai Indians",
    "Chennai Super Kings",
    "Royal Challengers Bengaluru",
    "Kolkata Knight Riders",
    "Rajasthan Royals"
])

print(fav_cricket_teams)

import pandas as pd

food_orders = pd.DataFrame({
    "Item": ["Pizza", "Biryani", "Burger"],
    "Restaurant": ["Domino's", "Behrouz Biryani", "McDonald's"],
    "Price": [299, 350, 199]
})

print(food_orders)

[1200, 54000, 780, 150000, 32000]

import pandas as pd

followers = pd.Series([1200, 54000, 780, 150000, 32000])

highest_index = followers.idxmax()
lowest_index = followers.idxmin()

print("Highest followers:")
print(followers[highest_index])

print("Lowest followers:")
print(followers[lowest_index])

import pandas as pd

playlist = pd.DataFrame({
    "Song": [
        "Perfect",
        "Until I Found You",
        "As It Was",
        "Die With A Smile"
    ],
    "Artist": [
        "Ed Sheeran",
        "Stephen Sanchez",
        "Harry Styles",
        "Lady Gaga & Bruno Mars"
    ],
    "Duration": [4.23, 2.57, 2.47, 4.11]
})

print(playlist[["Song", "Duration"]])

playlist[["Song", "Duration"]]

