# -*- coding: utf-8 -*-
"""session2 pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11bOp5aJmL6yu92U3KnKiXz79siM1bNHa
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()



ipl = pd.read_csv("data.csv")


print(ipl.head(10))

import pandas as pd

mobile_expenses = pd.DataFrame({
    "Date": [
        "2026-09-01",
        "2026-09-03",
        "2026-09-07",
        "2026-09-10",
        "2026-09-15",
        "2026-09-18",
        "2026-09-22",
        "2026-09-25"
    ],
    "Category": [
        "Mobile Recharge",
        "Internet",
        "Food",
        "Shopping",
        "Mobile Recharge",
        "Food",
        "Entertainment",
        "Internet"
    ],
    "Amount": [
        299,
        499,
        250,
        899,
        299,
        350,
        199,
        499
    ]
})

# Save as Excel file
mobile_expenses.to_excel(
    "mobile_expenses.xlsx",
    index=False
)

df_expenses = pd.read_excel("mobile_expenses.xlsx")

print(df_expenses)

print(df_expenses.tail(3))

import pandas as pd

from google.colab import files
uploaded = files.upload()

zomato = pd.read_csv("zomato_dataset.csv")

print(zomato.info())

print(zomato.describe())

filtered_data = ipl.head(20)

filtered_data.to_csv(
    "filtered_data.csv",
    index=False
)

print("First 20 rows exported successfully!")

ipl.to_excel(
    "ipl_analysis.xlsx",
    sheet_name="Analysis2024",
    index=False
)

print("IPL dataset exported successfully!")

