# -*- coding: utf-8 -*-
"""session6 pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J2a-d-YW6zMajTlpamBuRVqvel2LJDUp
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

spotify = pd.read_csv("spotify_songs.csv")

print("Before removing duplicates:")
print(spotify)


spotify = spotify.drop_duplicates(subset=["song"], keep="first")

print("\nAfter removing duplicates:")
print(spotify)

import pandas as pd

from google.colab import files
uploaded = files.upload()

flipkart = pd.read_csv("flipkart_reviews.csv")


duplicates_before = flipkart.duplicated(
    subset=["product_id", "user_id"]
).sum()

print("Duplicate reviews before:", duplicates_before)


flipkart_cleaned = flipkart.drop_duplicates(
    subset=["product_id", "user_id"],
    keep="first"
)


duplicates_after = flipkart_cleaned.duplicated(
    subset=["product_id", "user_id"]
).sum()

print("Duplicate reviews after:", duplicates_after)

import pandas as pd

from google.colab import files
uploaded = files.upload()

zomato = pd.read_csv("zomato_orders.csv")

Q1 = zomato["order_amount"].quantile(0.25)
Q3 = zomato["order_amount"].quantile(0.75)


IQR = Q3 - Q1


lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Limit:", lower_limit)
print("Upper Limit:", upper_limit)


outliers = zomato[
    (zomato["order_amount"] < lower_limit) |
    (zomato["order_amount"] > upper_limit)
]

print("\nOutlier orders:")
print(outliers[["order_id", "order_amount"]])

import pandas as pd


from google.colab import files
uploaded = files.upload()

ipl = pd.read_csv("ipl_ticket_sales.csv")


ipl["z_score"] = ipl(ipl["tickets_sold"])

outliers = ipl[ipl["z_score"].abs() > 2]

print(outliers[["date", "tickets_sold", "z_score"]])

import pandas as pd


from google.colab import files
uploaded = files.upload()

ipl = pd.read_csv("ipl_ticket_sales.csv")

def find_outliers(df, column):
    z_scores = ipl(df[column])

    outliers = df[z_scores.abs() > 2]

    return outliers


paytm = pd.DataFrame({
    "transaction_id": [101, 102, 103, 104, 105, 106, 107],
    "transaction_amount": [500, 700, 450, 600, 550, 650, 10000]
})


outliers = find_outliers(paytm, "transaction_amount")

print("Outlier transactions:")
print(outliers)



