# -*- coding: utf-8 -*-
"""session7 pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oETmtoljdrkCpbdvpjnybUBfG_mm4TMz
"""

import pandas as pd

data = {
    "ProductName": ["Laptop", "Mobile", "Headphones", "Keyboard", "Mouse"],
    "Price": [55000, 25000, 2000, 1500, 800],
    "Qty": [2, 3, 5, 4, 6]
}

df = pd.DataFrame(data)

df.to_csv("flipkart_sales.csv", index=False)

import pandas as pd

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("flipkart_sales.csv")

df["TotalValue"] = df["Price"] * df["Qty"]

print(df)

import pandas as pd

food = pd.DataFrame({
    "Item": ["Pizza", "Burger", "Pasta", "Sandwich"],
    "Price": [300, 200, 250, 150],
    "Qty": [2, 1, 3, 2]
})

food["DiscountedPrice"] = food["Price"].apply(
    lambda price: price * 0.90
)

print(food)

import pandas as pd

instagram = pd.DataFrame({
    "PostID": [101, 102, 103, 104],
    "Likes": [1500, 2000000, 850, 125000],
    "Comments": [200, 50000, 1200, 3000000]
})

print(instagram)

def format_number(num):

    if num >= 1000000:
        return f"{num / 1000000:.1f}M"

    elif num >= 1000:
        return f"{num / 1000:.1f}K"

    else:
        return str(num)

instagram[["Likes", "Comments"]] = instagram[
    ["Likes", "Comments"]
].applymap(format_number)

print(instagram)

import pandas as pd

zomato = pd.DataFrame({
    "Restaurant": ["Dominos", "McDonalds", "Burger King", "Subway"],
    "Price": [500, 300, 400, 250],
    "Qty": [2, 1, 3, 2],
    "DeliveryCharge": [50, 40, 60, 30]
})

zomato["FinalAmount"] = zomato.apply(
    lambda row: (row["Price"] * row["Qty"]) + row["DeliveryCharge"],
    axis=1
)

print(zomato)

import pandas as pd

myntra = pd.DataFrame({
    "Product": ["T-Shirt", "Jeans", "Shoes", "Jacket"],
    "Price": [1000, 2000, 3000, 2500],
    "Qty": [2, 1, 2, 1]
})

myntra["GST"] = myntra["Price"] * myntra["Qty"] * 0.05

print(myntra)

