# -*- coding: utf-8 -*-
"""session4 pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13aPBl_n2TBhtTex8PVageD54RkuPqJLw
"""

import pandas as pd

movies = pd.DataFrame({
    "title": [
        "3 Idiots",
        "Dangal",
        "Taare Zameen Par",
        "Zindagi Na Milegi Dobara",
        "Queen",
        "Andhadhun"
    ],
    "rating": [
        8.4,
        8.3,
        8.3,
        8.2,
        8.1,
        8.2
    ],
    "release_year": [
        2009,
        2016,
        2007,
        2011,
        2013,
        2018
    ]
})

# Sorting rating from highest to lowest
result = movies.sort_values(
    by="rating",
    ascending=False
)

print(result)

import pandas as pd

ipl_teams = pd.DataFrame({
    "team": [
        "Mumbai Indians",
        "Chennai Super Kings",
        "Royal Challengers Bengaluru",
        "Kolkata Knight Riders",
        "Rajasthan Royals"
    ],
    "points": [
        16,
        14,
        18,
        12,
        14
    ],
    "net_run_rate": [
        0.45,
        0.32,
        0.75,
        0.12,
        0.28
    ]
})

# Sorting index in descending order
result = ipl_teams.sort_index(ascending=False)

print(result)

import pandas as pd

youtube = pd.DataFrame({
    "video_title": [
        "Bollywood New Song",
        "IPL Highlights",
        "Travel Vlog",
        "Comedy Video",
        "Tech Review"
    ],
    "views": [
        5000000,
        4200000,
        1800000,
        3200000,
        1500000
    ],
    "likes": [
        450000,
        380000,
        150000,
        280000,
        120000
    ]
})

# Reset index and remove old index
youtube = youtube.reset_index(drop = True)

print(youtube)

import pandas as pd

restaurants = pd.DataFrame({
    "restaurant": [
        "Dominos",
        "Haldiram's",
        "McDonald's",
        "Burger King",
        "KFC"
    ],
    "rating": [
        4.2,
        4.4,
        4.1,
        4.3,
        4.0
    ]
})

print(restaurants)

import pandas as pd

flipkart = pd.DataFrame({
    "product_name": [
        "iPhone 15",
        "Samsung Galaxy S24",
        "OnePlus 12",
        "HP Laptop",
        "Boat Headphones",
        "Nike Shoes"
    ],
    "price": [
        69999,
        74999,
        59999,
        65999,
        1999,
        4999
    ],
    "discount": [
        10,
        20,
        15,
        30,
        40,
        25
    ]
})

# Sorting by discount from highest to lowest
flipkart = flipkart.sort_values(
    by="discount",
    ascending=False
)

# Reseting index
flipkart = flipkart.reset_index(drop=True)

print(flipkart)

