# -*- coding: utf-8 -*-
"""session10 pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Li8nusMrzSCYVpT3sfPQ9olCoQ6CpL8
"""

import pandas as pd

users = pd.DataFrame({
    "user_id": [1, 2, 3, 4, 5],
    "username": ["Aman", "Priya", "Rahul", "Sneha", "Karan"],
    "city": ["Mumbai", "Delhi", "Pune", "Indore", "Bhopal"]
})

print("Users:")
print(users)

orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104, 105, 106, 107],
    "user_id": [1, 2, 1, 3, 5, 2, 3],
    "order_amount": [500, 800, 1200, 300, 700, 450, 900]
})

print("Orders:")
print(orders)

result = pd.merge(
    users,
    orders,
    on="user_id",
    how="inner"
)

print(result)

result = pd.merge(
    users,
    orders,
    on="user_id",
    how="left"
)

print(result)

restaurants = pd.DataFrame({
    "restaurant_id": [1, 2, 3, 4],
    "name": ["Dominos", "Burger King", "Subway", "Cafe Coffee Day"],
    "city": ["Mumbai", "Delhi", "Pune", "Indore"]
})

zomato_reviews = pd.DataFrame({
    "review_id": [101, 102, 103, 104],
    "restaurant_id": [1, 2, 5, 3],
    "rating": [4.5, 4.0, 3.5, 5.0],
    "reviewer_city": ["Mumbai", "Delhi", "Bhopal", "Pune"]
})

result = pd.merge(
    restaurants,
    zomato_reviews,
    on="restaurant_id",
    how="outer"
)

print(result)

playlists = pd.DataFrame({
    "playlist_id": [101, 102, 103, 104, 105],
    "user_id": [1, 2, 3, 4, 5],
    "genre": ["Pop", "Rock", "Hip-Hop", "Jazz", "EDM"],
    "city": ["Mumbai", "Delhi", "Pune", "Indore", "Bhopal"]
})

user_profiles = pd.DataFrame({
    "user_id": [1, 2, 3, 4, 5],
    "username": ["Aman", "Priya", "Rahul", "Sneha", "Karan"],
    "city": ["Mumbai", "Delhi", "Mumbai", "Indore", "Bhopal"]
})

result = pd.merge(
    playlists,
    user_profiles,
    on=["user_id", "city"],
    how="inner"
)

print(result)

products = pd.DataFrame({
    "product_id": [101, 102, 103, 104],
    "name": ["Laptop", "Mobile", "Headphones", "Keyboard"],
    "category": ["Electronics", "Electronics", "Accessories", "Accessories"]
})

ratings = pd.DataFrame({
    "rating_id": [1, 2, 3, 4, 5],
    "product_id": [101, 102, 105, 103, 105],
    "rating": [5, 4, 3, 5, 2]
})

result = pd.merge(
    products,
    ratings,
    on="product_id"
)

print(result)

result = pd.merge(
    products,
    ratings,
    on="product_id",
    how="right"
)

print(result)

