# -*- coding: utf-8 -*-
"""session9 pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x_hzcOKBwpMFgNY-Uq42dhhJurZ5JBu2
"""

import pandas as pd

dates = pd.Series([
    "05-01-2026",
    "18-02-2026",
    "25-03-2026",
    "10-04-2026",
    "30-05-2026"
])


dates = pd.to_datetime(dates, format="%d-%m-%Y")

print(dates)

import pandas as pd

movies = pd.DataFrame({
    "movie": [
        "Inception",
        "Interstellar",
        "Titanic",
        "Avatar"
    ],
    "release_date": [
        "16-07-2010",
        "07-11-2014",
        "19-12-1997",
        "18-12-2009"
    ]
})

# Convert release_date to datetime
movies["release_date"] = pd.to_datetime(
    movies["release_date"],
    format="%d-%m-%Y"
)


movies["year"] = movies["release_date"].dt.year
movies["month"] = movies["release_date"].dt.month
movies["day"] = movies["release_date"].dt.day

print(movies)

import pandas as pd

dates = pd.date_range(
    start=pd.Timestamp.today(),
    periods=7,
    freq="D"
)

print(dates)

import pandas as pd

zomato = pd.DataFrame({
    "user_id": [101, 102, 103, 104],
    "start_date": [
        "01-01-2026",
        "15-03-2026",
        "10-06-2026",
        "20-08-2026"
    ]
})


zomato["start_date"] = pd.to_datetime(
    zomato["start_date"],
    format="%d-%m-%Y"
)


today = pd.Timestamp.today().normalize()


zomato["tenure_days"] = (today - zomato["start_date"]).dt.days

print(zomato)

