# -*- coding: utf-8 -*-
"""session12 pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Cme4tG1GK0hQm8vRFWvM3v3l2eMAqhE
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

ipl = pd.read_csv("dataset.csv")

team_runs = (
    ipl.groupby("batting_team")["total_runs"]
       .sum()
       .reset_index()
)

print(team_runs)

import pandas as pd

zomato = pd.DataFrame({
    "city": [
        "Mumbai", "Mumbai", "Delhi",
        "Delhi", "Pune", "Pune",
        "Mumbai", "Delhi"
    ],
    "restaurant": [
        "Dominos", "Dominos", "Dominos",
        "McDonalds", "McDonalds", "McDonalds",
        "Subway", "Subway"
    ],
    "order_amount": [
        500, 700, 400,
        300, 450, 550,
        350, 600
    ]
})

result = (
    zomato
    .groupby(["city", "restaurant"])
    .agg(
        average_order_amount=("order_amount", "mean")
    )
    .reset_index()
)

print(result)

import pandas as pd

sales = pd.DataFrame({
    "category": [
        "Electronics", "Electronics", "Electronics",
        "Fashion", "Fashion", "Fashion",
        "Home", "Home"
    ],
    "region": [
        "North", "North", "South",
        "North", "South", "South",
        "North", "South"
    ],
    "sales": [
        50000, 70000, 60000,
        30000, 45000, 55000,
        25000, 35000
    ],
    "units_sold": [
        100, 140, 120,
        80, 100, 110,
        60, 75
    ]
})

result = (
    sales
    .groupby(["category", "region"])
    .agg(
        total_sales=("sales", "sum"),
        average_units_sold=("units_sold", "mean")
    )
    .reset_index()
)

print(result)

import pandas as pd

df = pd.DataFrame({
    "region": [
        "North", "North", "North",
        "South", "South", "West",
        "West"
    ],
    "revenue": [
        50000, 70000, 40000,
        60000, 80000, 30000,
        55000
    ]
})

result = (
    df.groupby("region")
      .agg({
          "revenue": ["sum", "max", "min"]
      })
)

print(result)

import pandas as pd

spotify = pd.DataFrame({
    "artist": [
        "Taylor Swift", "Ed Sheeran", "Drake",
        "Ariana Grande", "Taylor Swift", "Drake",
        "Ed Sheeran", "Ariana Grande"
    ],
    "genre": [
        "Pop", "Pop", "Hip-Hop",
        "Pop", "Pop", "Hip-Hop",
        "Pop", "Pop"
    ],
    "streams": [
        5000000, 4000000, 7000000,
        6000000, 3000000, 5000000,
        2000000, 4500000
    ]
})

result = (
    spotify
    .groupby("genre")
    .agg(
        total_streams=("streams", "sum"),
        average_streams=("streams", "mean")
    )
)

result = (
    spotify
    .groupby("genre")
    .agg(
        total_streams=("streams", "sum"),
        average_streams=("streams", "mean")
    )
)

