# -*- coding: utf-8 -*-
"""session11 pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bxFjuAkxT38VxJgRwpZI8AnSWzyGCI70
"""

import pandas as pd

jan_orders = pd.DataFrame({
    "order_id": [101, 102, 103],
    "customer": ["Aman", "Priya", "Rahul"],
    "amount": [450, 300, 550]
})

feb_orders = pd.DataFrame({
    "order_id": [104, 105, 106],
    "customer": ["Sneha", "Karan", "Neha"],
    "amount": [700, 250, 400]
})

all_orders = pd.concat(
    [jan_orders, feb_orders],
    ignore_index=True
)

print(all_orders)

products = pd.DataFrame({
    "product_id": [101, 102, 103, 104],
    "product": ["Laptop", "Mobile", "Headphones", "Keyboard"]
})

ratings = pd.DataFrame({
    "rating": [4.5, 4.2, 4.7, 4.0]
})

result = pd.concat(
    [products, ratings],
    axis=1
)

print(result)

import pandas as pd

spotify = pd.DataFrame({
    "user": [
        "Aman", "Aman", "Aman",
        "Priya", "Priya", "Priya",
        "Rahul", "Rahul", "Rahul"
    ],
    "day": [
        "Monday", "Tuesday", "Wednesday",
        "Monday", "Tuesday", "Wednesday",
        "Monday", "Tuesday", "Wednesday"
    ],
    "streams": [
        100, 150, 120,
        200, 180, 220,
        80, 90, 110
    ]
})

print(spotify)

result = spotify.pivot(
    index="user",
    columns="day",
    values="streams"
)

print(result)

import pandas as pd

zomato = pd.DataFrame({
    "restaurant": [
        "Dominos", "Dominos",
        "McDonalds", "McDonalds",
        "Subway", "Subway"
    ],
    "month": [
        "January", "February",
        "January", "February",
        "January", "February"
    ],
    "total_amount": [
        500, 700,
        300, 400,
        450, 550
    ]
})

result = zomato.pivot_table(
    index="restaurant",
    columns="month",
    values="total_amount",
    aggfunc="mean"
)

print(result)

