# -*- coding: utf-8 -*-
"""session8 pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DMToMPAhA2QRppWvpNsTIETQ0uxv5srQ
"""

import pandas as pd

instagram = pd.DataFrame({
    "username": [
        "CoolDude",
        "foodieQueen",
        "TravelLover",
        "FIT_Girl",
        "MovieFan"
    ]
})

instagram["username"] = instagram["username"].str.lower()

print(instagram)

import pandas as pd

songs = pd.Series([
    "Perfect Remix",
    "Blinding Lights Remix",
    "Shape of You",
    "Levitating Remix",
    "Stay Remix"
])

cleaned_songs = songs.str.replace("Remix", "", regex=False)

print(cleaned_songs)

cleaned_songs = songs.str.replace("Remix", "", regex=False).str.strip()

print(cleaned_songs)

import pandas as pd

zomato = pd.DataFrame({
    "review": [
        "The food was good and delivery was fast",
        "Amazing taste",
        "Delivery was very late",
        "Good packaging and service",
        "FAST DELIVERY and great food"
    ]
})

result = zomato[
    zomato["review"].str.contains("delivery", case=False, na=False)
]

print(result)

import pandas as pd

categories = pd.Series([
    "Electronics/Mobiles/Smartphones",
    "Home/Kitchen/Appliances",
    "Fashion/Men/Shirts",
    "Beauty/Skincare/Facewash"
])

df = pd.DataFrame({
    "CategoryPath": categories
})

df["MainCategory"] = df["CategoryPath"].str.split("/").str[0]

print(df)

import pandas as pd

youtube = pd.DataFrame({
    "title": [
        "How to Learn Python",
        "Pandas Tutorial for Beginners",
        "Data Analyst Roadmap",
        "Power BI Complete Course"
    ]
})

youtube["title"] = youtube["title"].str.upper().str.replace(" ", "_", regex=False)

print(youtube)

