# -*- coding: utf-8 -*-
"""session3 pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OiSD3l0BlFl-2mL1WbJ2hG3PK1GJQoag
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

movies = pd.read_csv("imdb_top_1000.csv")

movies = movies.rename(columns={
    "Series_Title": "title",
    "Genre": "genre",
    "IMDB_Rating": "rating",
    "Gross": "box_office"
})

print(movies.loc[:, ["title", "rating"]])

import pandas as pd

from google.colab import files
uploaded = files.upload()

flipkart = pd.read_csv("Dataset.csv")

flipkart = flipkart.rename(columns={
    "Product_name": "product_name",
    "Price": "price"
})

print(flipkart.iloc[:10, :])

orders = pd.DataFrame({
    "restaurant": [
        "Dominos",
        "Biryani Blues",
        "McDonald's",
        "Burger King",
        "Haldiram's",
        "KFC"
    ],
    "order_amount": [
        450,
        650,
        350,
        750,
        900,
        620
    ],
    "delivery_time": [
        35,
        45,
        30,
        50,
        40,
        45
    ]
})

result = orders[orders["order_amount"] > 500]

print(result)

import pandas as pd

from google.colab import files
uploaded = files.upload()

spotify = pd.read_csv("artists.csv")

spotify["duration"] = spotify["duration_ms"] / 1000

result = spotify.query(
    "streams > 1000000 and duration < 180"
)

print(result)

import pandas as pd

from google.colab import files
uploaded = files.upload()

ipl = pd.read_csv("data.csv")

result = ipl[
    (ipl["total_runs"] >= 180) &
    (ipl["total_runs"] <= 220)
]

print(result)

