# -*- coding: utf-8 -*-
"""session5 pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_cClFRlAQa7cXbABMy9qRnsYP7QJ7U9Y
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

ipl = pd.read_csv("data.csv")

missing_player = ipl[ipl["player_of_match"].isna()]

print("IPL players with missing age:")
print(missing_player)

import pandas as pd


from google.colab import files
uploaded = files.upload()

zomato = pd.read_csv("zomato_dataset.csv")


cleaned_zomato = zomato.dropna(
    subset=["Delivery Rating"]
)

print(cleaned_zomato)

import pandas as pd

from google.colab import files
uploaded = files.upload()

flipkart = pd.read_csv("Dataset.csv")

print(flipkart.columns)


flipkart["Rate"] = flipkart["Rate"].fillna(flipkart["Rate"].mean())

print(flipkart)

import pandas as pd

from google.colab import files
uploaded = files.upload()

spotify = pd.read_csv("songs_normalize.csv")


spotify["duration"] = spotify["duration_ms"] / 1000


median_duration = spotify["duration"].median()


spotify["duration"] = spotify["duration"].fillna(median_duration)

spotify.to_csv("spotify_cleaned.csv", index=False)

print(spotify)

import pandas as pd

from google.colab import files
uploaded = files.upload()

instagram = pd.read_csv("instagram_users.csv")

print(instagram)

instagram["followers"] = instagram["followers"].fillna(0)

print(instagram)

