# -*- coding: utf-8 -*-
"""session14 pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10WVEK5jHGf6RVOy0DSb1UK7qp7DgB4le
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

ipl_df = pd.read_csv("data.csv")

print(ipl_df.head(5))

ipl_df = ipl_df.dropna(subset=["winner"])

ipl_df = ipl_df.reset_index(drop=True)

print(ipl_df.head())

import numpy as np

conditions = [
    ipl_df["win_by_runs"] > 0,
    ipl_df["win_by_wickets"] > 0
]

choices = [
    "Runs",
    "Wickets"
]

ipl_df["match_margin_type"] = np.select(
    conditions,
    choices,
    default="Tie/No Result"
)

print(
    ipl_df[
        ["team1", "team2", "winner",
         "win_by_runs", "win_by_wickets",
         "match_margin_type"]
    ].head(10)
)

team_data = pd.DataFrame({
    "team": [
        "Mumbai Indians",
        "Chennai Super Kings",
        "Royal Challengers Bangalore",
        "Kolkata Knight Riders",
        "Delhi Daredevils",
        "Rajasthan Royals",
        "Kings XI Punjab",
        "Sunrisers Hyderabad"
    ],
    "home_city": [
        "Mumbai",
        "Chennai",
        "Bengaluru",
        "Kolkata",
        "Delhi",
        "Jaipur",
        "Mohali",
        "Hyderabad"
    ]
})

print(team_data)

ipl_df = pd.merge(
    ipl_df,
    team_data,
    left_on="team1",
    right_on="team",
    how="left"
)

ipl_df = ipl_df.rename(
    columns={"home_city": "team1_home_city"}
)

ipl_df = ipl_df.drop(columns=["team"])

ipl_df = pd.merge(
    ipl_df,
    team_data,
    left_on="team2",
    right_on="team",
    how="left"
)

ipl_df = ipl_df.rename(
    columns={"home_city": "team2_home_city"}
)

ipl_df = ipl_df.drop(columns=["team"])

print(
    ipl_df[
        ["team1", "team1_home_city",
         "team2", "team2_home_city"]
    ].head(10)
)

wins = pd.pivot_table(
    ipl_df,
    index="winner",
    columns="season",
    values="id",
    aggfunc="count",
    fill_value=0
)

print(wins)

